name: RoboPD2 Web CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    # Specify the custom runner label
    runs-on: robopd2-runners
    
    container:
      image: gcr.io/kaniko-project/executor:latest
      options: --user root
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build and Push with Kaniko
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "$DOCKERHUB_USERNAME" "$DOCKERHUB_TOKEN" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
          
          /kaniko/executor \
            --context=$GITHUB_WORKSPACE \
            --dockerfile=$GITHUB_WORKSPACE/Dockerfile \
            --destination=$DOCKERHUB_USERNAME/your-image-name:latest \
            --destination=$DOCKERHUB_USERNAME/your-image-name:${{ github.sha }}