name: Docker Image Build with Kaniko

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    # Specify the custom runner label
    runs-on: robopd2-runners
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and Push with Kaniko
      uses: addnab/docker-run-action@v3
      with:
        image: gcr.io/kaniko-project/executor:latest
        options: >
          -v ${{ github.workspace }}:/workspace
          -v /kaniko/.docker/config.json:/kaniko/.docker/config.json
        run: >
          /kaniko/executor 
          --context=/workspace 
          --dockerfile=/workspace/Dockerfile 
          --destination=${{ secrets.DOCKERHUB_USERNAME }}/robopd2-web:latest
          --destination=${{ secrets.DOCKERHUB_USERNAME }}/robopd2-web:${{ github.sha }}